export const PAGE_LIST_REQUEST = "PAGE_LIST_REQUEST"
export const PAGE_LIST_SUCCESS = "PAGE_LIST_SUCCESS"
export const PAGE_LIST_FAIL = "PAGE_LIST_FAIL"

export const PAGE_DETAIL_REQUEST = "PAGE_DETAIL_REQUEST"
export const PAGE_DETAIL_SUCCESS = "PAGE_DETAIL_SUCCESS"
export const PAGE_DETAIL_FAIL = "PAGE_DETAIL_FAIL"

export const PAGE_EDIT_REQUEST = "PAGE_EDIT_REQUEST"
export const PAGE_EDIT_SUCCESS = "PAGE_EDIT_SUCCESS"
export const PAGE_EDIT_FAIL = "PAGE_EDIT_FAIL"
export const PAGE_EDIT_RESET = "PAGE_EDIT_RESET"
